name: Check for Free Games on Epic Games Store

on:
  schedule:
    - cron: '0 16 * * THU'  # Schedule to run every Thursday at 16:00

jobs:
  check_free_games:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Run script
        run: python update_free_games_readme.py
        
      - name: Update README with free games
        run: |
          current_date=$(date +'%Y-%m-%d')
          git pull  
          cat README.md
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit --amend -m "update free games from epic games store"
            git push -f
          fi
          
      - name: Clear commit
        run: |
          git checkout --orphan tmp
          git commit -m "$(date)"
          git branch -D main
          git branch -m tmp main
          git push --set-upstream origin main -f